apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: eshop-modernized-wcf
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: eshop-modernized-wcf
    spec:
      containers:
      - name: eshop-modernized-wcf
        image: eshop/wcfservice
        ports:
        - containerPort: 83
        imagePullPolicy: Always
        env:
        - name: ConnectionString
          value: "Server=sql-data;Database=Microsoft.eShopOnContainers.Services.CatalogDb;User Id=sa;Password=Pass@word"
      nodeSelector:
       beta.kubernetes.io/os: windows
---
apiVersion: v1
kind: Service
metadata:
  name: eshop-modernized-wcf
  labels:
    app: eshop-modernized-wcf
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 83
  selector:
    app: eshop-modernized-wcf